# frozen_string_literal: true

module Security
  module VulnerabilityScanning
    class CreateVulnerabilityService
      # This service creates vulnerabilities for an advisory and affected SBOM components.
      # Continuous vulnerability scans are expensive to perform, so the service tries to
      # handle errors gracefully whenever possible. In other words, if we cannot create a
      # vulnerability for Project A we still attempt to create one for Project B, Project C...Project N.
      #
      # @param advisory [::Gitlab::VulnerabilityScanning::Advisory] :advisory
      # @param affected_components [Array<::Gitlab::VulnerabilityScanning::PossiblyAffectedComponent>]
      #   :affected_components
      #
      # @return [ServiceResponse] The service responds with a success if one or more vulnerabilities were created,
      #   and an error if no vulnerabilities could be created. If successful, the service response payload contains
      #   a `vulnerability_ids` key with the IDs of the new vulnerabilities. In addition, it will always return the
      #   `project_ids_with_upsert` and `project_ids_with_error` arrays fields. These fields contain the IDs of
      #   projects where we successfully upserted a vulnerability and the IDs of the projects where
      #   we encountered an error during creation.
      def self.execute(...)
        new(...).execute
      end

      def initialize(advisory:, affected_components:)
        @advisory = advisory
        @affected_components = affected_components
        @project_ids_with_upsert = Set[]
        @project_ids_with_error = Set[]
      end

      def execute
        vulnerability_ids = ::Security::Ingestion::IngestCvsSliceService.execute(finding_maps)
        ServiceResponse.success(message: "Vulnerabilities were created",
          payload: {
            vulnerability_ids: vulnerability_ids,
            project_ids_with_upsert: project_ids_with_upsert.to_a,
            project_ids_with_error: project_ids_with_error.to_a
          })
      rescue StandardError => error
        process_unrecoverable_error(error)
      end

      private

      attr_reader :advisory, :affected_components, :project_ids_with_upsert, :project_ids_with_error

      def report_scanner
        ::Gitlab::VulnerabilityScanning::SecurityScanner.fabricate
      end

      def scanner_for_project(project)
        ::Gitlab::VulnerabilityScanning::SecurityScanner.find_or_create_for_project!(project)
      end

      def finding_for_affected_component(affected_component)
        purl_type = affected_component.purl_type
        builder = ::Gitlab::VulnerabilityScanning::FindingBuilder.for_purl_type!(purl_type)
        builder.new(
          project: affected_component.project,
          pipeline: affected_component.pipeline,
          scanner: report_scanner,
          sbom_source: affected_component.source,
          advisory: advisory,
          affected_component: affected_component
        ).finding
      end

      def finding_maps
        maps = affected_components.filter_map do |affected_component|
          if affected_component.pipeline.user.nil?
            track_missing_author_error_for_project_id(affected_component.project.id)
            next
          end

          track_upsert_for_project_id(affected_component.project.id)
          pipeline = affected_component.pipeline
          finding = finding_for_affected_component(affected_component)
          scanner_id = scanner_for_project(affected_component.project).id
          FindingMap.new(pipeline: pipeline, report_finding: finding, scanner_id: scanner_id)
        end

        # Since continuous vulnerability scanning is expensive to perform,
        # we only raise an error if we failed to build all findings, and
        # track individual ones in Sentry.
        raise StandardError, "No vulnerability scanning finding maps could be created" if maps.empty?

        maps
      end

      def track_upsert_for_project_id(project_id)
        project_ids_with_upsert.add(project_id)
      end

      def track_missing_author_error_for_project_id(project_id)
        ::Gitlab::ErrorTracking.track_exception(
          ArgumentError.new('Pipeline must have a corresponding user to use as vulnerability author'),
          message: 'Skipping vulnerability creation for project',
          project_id: project_id,
          advisory_xid: advisory.xid)

        project_ids_with_error.add(project_id)
      end

      def process_unrecoverable_error(error)
        ::Gitlab::ErrorTracking.track_exception(error,
          message: "Continuous vulnerability scanning failed to create vulnerabilities",
          project_ids_with_upsert: project_ids_with_upsert.to_a,
          project_ids_with_error: project_ids_with_error.to_a,
          advisory_xid: advisory.xid)

        ServiceResponse.error(message: "Vulnerabilities were not created", payload: {
          error: error,
          project_ids_with_upsert: project_ids_with_upsert.to_a,
          project_ids_with_error: project_ids_with_error.to_a
        })
      end
    end
  end
end
